name: unit tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        sudo apt install -y libopenmpi-dev
        python -m pip install --upgrade pip
        if [ -f requirements/baselines.txt ]; then 
          cat requirements/baselines.txt | grep -v baselines | xargs pip install --ignore-installed
          cat requirements/baselines.txt | grep baselines | xargs pip install --ignore-installed
        fi
    - name: Test python code with unittest
      run: |
        python -m unittest discover -s tests/